global:
  domain: argocd.example.com

server:
  ingress:
    enabled: true
    ingressClassName: webapprouting.kubernetes.azure.com  
    annotations:
      kubernetes.io/tls-acme: "true"
      external-dns.alpha.kubernetes.io/hostname: argocd.example.com
    hostname: argocd.example.com
    path: /
    pathType: Prefix
    tls: true
    extraTls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.example.com

configs:
  params:
    server.insecure: true
  cm:
    admin.enabled: "true"
    url: https://argocd.example.com

repoServer:
  autoscaling:
    enabled: false

applicationSet:
  enabled: true

notifications:
  enabled: false
